extends Node

class_name PuzzleMasks

const MASKS:Array = [
	preload("res://sprites/puzzle-masks/p11.png"),
	preload("res://sprites/puzzle-masks/p12.png"),
	preload("res://sprites/puzzle-masks/p13.png"),
	preload("res://sprites/puzzle-masks/p14.png"),
	preload("res://sprites/puzzle-masks/p15.png"),
	preload("res://sprites/puzzle-masks/p16.png"),
	preload("res://sprites/puzzle-masks/p17.png"),
	preload("res://sprites/puzzle-masks/p21.png"),
	preload("res://sprites/puzzle-masks/p22.png"),
	preload("res://sprites/puzzle-masks/p23.png"),
	preload("res://sprites/puzzle-masks/p24.png"),
	preload("res://sprites/puzzle-masks/p25.png"),
	preload("res://sprites/puzzle-masks/p26.png"),
	preload("res://sprites/puzzle-masks/p27.png"),
	preload("res://sprites/puzzle-masks/p31.png"),
	preload("res://sprites/puzzle-masks/p32.png"),
	preload("res://sprites/puzzle-masks/p33.png"),
	preload("res://sprites/puzzle-masks/p34.png"),
	preload("res://sprites/puzzle-masks/p35.png"),
	preload("res://sprites/puzzle-masks/p36.png"),
	preload("res://sprites/puzzle-masks/p37.png"),
	preload("res://sprites/puzzle-masks/p41.png"),
	preload("res://sprites/puzzle-masks/p42.png"),
	preload("res://sprites/puzzle-masks/p43.png"),
	preload("res://sprites/puzzle-masks/p44.png"),
	preload("res://sprites/puzzle-masks/p45.png"),
	preload("res://sprites/puzzle-masks/p46.png"),
	preload("res://sprites/puzzle-masks/p47.png"),
	preload("res://sprites/puzzle-masks/p51.png"),
	preload("res://sprites/puzzle-masks/p52.png"),
	preload("res://sprites/puzzle-masks/p53.png"),
	preload("res://sprites/puzzle-masks/p54.png"),
	preload("res://sprites/puzzle-masks/p55.png"),
	preload("res://sprites/puzzle-masks/p56.png"),
	preload("res://sprites/puzzle-masks/p57.png"),
]
